---
title: "WeCare Progress Report"
author: "Michael Wu"
date: "`r Sys.Date()`"
output: 
  officedown::rdocx_document:
    mapstyles:
      Normal: ['First Paragraph']
    reference_docx: word_template.docx
---

```{r setup, include=FALSE}
# knitr global settings
knitr::opts_chunk$set(
  echo = FALSE, 
  fig.cap = TRUE,
  warning = FALSE, 
  cache = FALSE,
  message = FALSE,
  error = T,
  results="asis",
  tab.cap.style = "Table Caption",
  tab.cap.pre = "Table ",
  tab.cap.sep = ": ",
  fig.cap.style = "Image Caption",
  fig.cap.pre = "Figure ",
  fig.cap.sep = ": ")

options(yaml.eval.expr = TRUE)

library(officer)
library(officedown)
library(targets)
# source(here::here("R/utils.R"))
# source(here::here("R/table_functions.R"))
```

```{r, include = F}
# vertical and horizontal page margin set up
ps <- officer::prop_section(
  page_margins = officer::page_mar(
    bottom = 1,
    top = 1,
    right = 1,
    left = 1,
    header = 0.5,
    footer = 0.5,
    gutter = 0),
  type = "continuous"
)
```

`r officer::block_section(ps)`
\newpage

## Table of content

<!---BLOCK_TOC--->

## List of figures

<!---BLOCK_TOC{seq_id: 'fig'}--->

## List of tables

<!---BLOCK_TOC{seq_id: 'tab'}--->

`r officer::block_section(ps)`
\newpage

<!---BLOCK_LANDSCAPE_START--->

```{r tab_enrollment, tab.cap="Summary of Enrollment", tab.id = "tab_enrollment"}
tar_read(t_enrollment)
```

\newpage

```{r tab_weekly_enrollment, tab.cap="Number of Youths Enrolled during Each One-Week Recruitment Period", tab.id = "tab_weekly_enrollment"}
tar_read(t_weekly_enrollment)
```

\newpage

```{r tab_recruitment, tab.cap="Detailed Recruitment Information", tab.id = "tab_demo"}
tar_read(t_recruitment)
```

\newpage

```{r tab_assignment, tab.cap="Treatment/Control Group Assignment among Enrolled Youths", tab.id = "tab_assignment"}
tar_read(t_assignment)
```

\newpage

<!---BLOCK_LANDSCAPE_STOP--->

```{r tab_trigger_rmp, tab.cap="Triggered Risk Management Protocol during Baseline", tab.id = "tab_trigger_rmp"}
tar_read(t_trigger_rmp)
```

\newpage

<!---BLOCK_LANDSCAPE_START--->

```{r tab_demo, tab.cap="Demographics of Enrolled Subjects (DSMB Chart)", tab.id = "tab_demo"}
tar_read(t_demo)
```

\newpage

<!---BLOCK_LANDSCAPE_STOP--->

```{r tab_monthly_enrollment, tab.cap="Enrollment Table: Projected vs. Actual by Time (Cumulative over Time)", tab.id = "tab_monthly_enrollment"}
tar_read(t_monthly_enrollment)
```

\newpage

<!---BLOCK_LANDSCAPE_START--->

```{r fig_monthly_enrollment, fig.cap="Enrollment Graph: Projected vs. Actual by Time (Cumulative over Time)", fig.id = "fig_monthly_enrollment", fig.width=10, fig.height=5, fig.dpi=600}
tar_read(p_monthly_enrollment)
```

<!---BLOCK_LANDSCAPE_STOP--->
